### ISSUE TITLE
Email Authentication 

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/tradewinds#15]
- [x] Email Validator

- [x] Password Validator

- [x] Progress Indicator either on the button or the whole screen

**Comment by rahulgambhir** [comment]
Please assign me this.

**Comment by 0Vipin0** [comment]
Is there anything left in this one @himanshusharma89  @rahulgambhir ? I don't think so, but still want to clarify before closing this.

**Comment by himanshusharma89** [comment]
> Is there anything left in this one @himanshusharma89 @rahulgambhir ? I don't think so, but still want to clarify before closing this.

No, I am closing this.
